name: Config

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: 'qa'
        options: 
          - qa
          - dev
      apihost:
        type: choice
        required: true
        default: 'fqdn-qa'
        options:
          - https://fqdn-qa
          - https://fqdn-dev

permissions:
    id-token: write
    contents: read
    packages: read

